spring:
  application:
    name: Teste-BPM

  datasource:
    url: jdbc:mysql://mysql:3306/hotel_bpm?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

springdoc:
  swagger-ui: /swagger-ui.html
